import { Contact }    from '../components/Contact';
import Head           from 'next/head';
import { ReviewForm } from '@/components/ReviewForm';
import styles         from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>CABINS PROJECT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid justify-center'>
        <main className={styles.main}>
          <Contact />
          {/* <ReviewForm /> */}
        </main>
      </div>
    </>
  );
}
